Vinodhmohan91 dev 3
IBM/sms-spam-filter-using-hortonworks pull request #10
Opened 2018-10-26 23:03 UTC by vinodhmohan91

Added and edited content to show the steps to save the spam filter model in both Watson Studio Local and Remote HDP cluster. Also, has steps to do a batch scoring and model evaluation.

2018-10-26 23:22 UTC, rhagarty requested changes
couple small nits

2018-10-26 23:22 UTC, rhagarty commented on README.md
> +    - Save the Spam Filter pyspark model in HDP cluter and import the model into Wastson Studio Local.
typos - cluster and Watson

2018-10-26 23:22 UTC, rhagarty commented on README.md
> +After training the model (step 3) in remote HDP cluster, the model exists in the memory of the remote session. Write the model to a HDFS location and copy it to local node as show below.
"as shown below"

2018-10-26 23:22 UTC, rhagarty commented on README.md
> +Click any one of the above models to test and score. Provide a test message as `Input` and press `submit` to do a real time scoring.
"real-time"

2018-10-26 23:22 UTC, rhagarty commented on README.md
> +Select the `Execution Type`, `Input data set` and `Output data set` and click `Generate batch script` to do a batch scoring.
"do a batch scoring run" or maybe "run a batch scoring job"?

2018-10-27 02:05 UTC, vinodhmohan91 commented on README.md
> +    - Save the Spam Filter pyspark model in HDP cluter and import the model into Wastson Studio Local.
Done

2018-10-27 02:05 UTC, vinodhmohan91 commented on README.md
> +After training the model (step 3) in remote HDP cluster, the model exists in the memory of the remote session. Write the model to a HDFS location and copy it to local node as show below.
Done

2018-10-27 02:05 UTC, vinodhmohan91 commented on README.md
> +Click any one of the above models to test and score. Provide a test message as `Input` and press `submit` to do a real time scoring.
Done

2018-10-27 02:05 UTC, vinodhmohan91 commented on README.md
> +Select the `Execution Type`, `Input data set` and `Output data set` and click `Generate batch script` to do a batch scoring.
Done

2018-10-27 02:06 UTC, vinodhmohan91 commented
Made the changes requested. Please review and merge.

2018-10-27 02:41 UTC, rhagarty approved these changes

2018-10-27 02:41 UTC, merged